# Nesse aqruivo vou subir dois containers a API e o DB
version: '3'

services:
  API:
    build: .
    container_name: crud-api
    tty: true
    command: sh
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    env_file:
      - .env

  DB:
    container_name: crud-db
    ports:
      - 3306:3306
    image: mysql:8.0.32
    env_file:
      - .env
